server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push #or 192.168.x.x

scrape_configs:
  - job_name: exnodebackapi_logs
    static_configs:
      - targets:
          - exnodebackapi_1 #ports are not required
        labels:
          job: varlogs
          instance: exnodebackapi_1
          __path__: /var/log/app/*
      - targets:
          - exnodebackapi_2
        labels:
          job: varlogs
          instance: exnodebackapi_2
          __path__: /var/log/app/*

 
      


